// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Tunneler is an autogenerated mock type for the Tunneler type
type Tunneler struct {
	mock.Mock
}

// StartTunnel provides a mock function with given fields: nodeID, tunnelURL, token
func (_m *Tunneler) StartTunnel(nodeID string, tunnelURL string, token string) {
	_m.Called(nodeID, tunnelURL, token)
}
