// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	gocron "github.com/go-co-op/gocron"
	mock "github.com/stretchr/testify/mock"
)

// Scheduler is an autogenerated mock type for the Scheduler type
type Scheduler struct {
	mock.Mock
}

// Every provides a mock function with given fields: interval
func (_m *Scheduler) Every(interval uint64) *gocron.Scheduler {
	ret := _m.Called(interval)

	var r0 *gocron.Scheduler
	if rf, ok := ret.Get(0).(func(uint64) *gocron.Scheduler); ok {
		r0 = rf(interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocron.Scheduler)
		}
	}

	return r0
}

// StartBlocking provides a mock function with given fields:
func (_m *Scheduler) StartBlocking() {
	_m.Called()
}
