// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	lb "github.com/NodeFactoryIo/vedran-daemon/internal/lb"
	mock "github.com/stretchr/testify/mock"

	telemetry "github.com/NodeFactoryIo/vedran-daemon/internal/telemetry"
)

// TelemetryInterface is an autogenerated mock type for the TelemetryInterface type
type TelemetryInterface struct {
	mock.Mock
}

// StartSendingTelemetry provides a mock function with given fields: scheduler, client, nodeMetrics
func (_m *TelemetryInterface) StartSendingTelemetry(scheduler telemetry.Scheduler, client *lb.Client, nodeMetrics string) error {
	ret := _m.Called(scheduler, client, nodeMetrics)

	var r0 error
	if rf, ok := ret.Get(0).(func(telemetry.Scheduler, *lb.Client, string) error); ok {
		r0 = rf(scheduler, client, nodeMetrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
