// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	lb "github.com/NodeFactoryIo/vedran-daemon/internal/lb"
	mock "github.com/stretchr/testify/mock"

	node "github.com/NodeFactoryIo/vedran-daemon/internal/node"

	scheduler "github.com/NodeFactoryIo/vedran-daemon/internal/scheduler"
)

// Telemetry is an autogenerated mock type for the Telemetry type
type Telemetry struct {
	mock.Mock
}

// StartSendingTelemetry provides a mock function with given fields: _a0, lbClient, nodeClient
func (_m *Telemetry) StartSendingTelemetry(_a0 scheduler.Scheduler, lbClient *lb.Client, nodeClient node.Client) {
	_m.Called(_a0, lbClient, nodeClient)
}
