on: [pull_request, push]
name: Tests MacOS

jobs:
  build:
    name: Run tests
    runs-on: maxos-latest
    env:
      GO111MODULE: "on"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: make build

      - name: Run tests
        shell: bash
        run: make test
